// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AclRole
 *
 * Possible acl roles
 */
export const zAclRole = z.enum([
    'red',
    'blue',
    'spectator'
]);

/**
 * AclBase
 *
 * Shared properties for multiple acl schemas
 */
export const zAclBase = z.object({
    assessment_role: zAclRole.optional().default('spectator'),
    user_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * AclRead
 *
 * Properties to return via API for general acl requests
 */
export const zAclRead = z.object({
    assessment_role: zAclRole.optional().default('spectator'),
    user_id: z.uuid(),
    assessment_id: z.uuid(),
    id: z.uuid()
});

/**
 * ActivityAssetRole
 *
 * Possible asset roles in an activity
 */
export const zActivityAssetRole = z.enum([
    'source',
    'target',
    'tool',
    'log_source',
    'prevention_source',
    'alert_source',
    'stakeholder_notification_source'
]);

/**
 * ActivityAssetUpdate
 *
 * Schema for updating activity assets
 */
export const zActivityAssetUpdate = z.object({
    asset_ids: z.array(z.uuid())
});

/**
 * ActivityBase
 *
 * Assessment activity base model
 */
export const zActivityBase = z.object({
    name: z.string(),
    mitre_tactic: z.string(),
    mitre_technique: z.string()
});

/**
 * ActivityGroupBase
 *
 * Shared properties for activity groups
 */
export const zActivityGroupBase = z.object({
    name: z.string(),
    visible: z.boolean().optional().default(false)
});

/**
 * ActivityGroupRead
 *
 * Properties to return via API
 */
export const zActivityGroupRead = z.object({
    name: z.string(),
    visible: z.boolean().optional().default(false),
    id: z.uuid(),
    deleted: z.boolean(),
    is_default: z.boolean(),
    activity_group_position: z.int()
});

/**
 * ActivityGroupReorder
 *
 * Schema for reordering activities within a activity group
 */
export const zActivityGroupReorder = z.object({
    activity_group_ids: z.array(z.uuid())
});

/**
 * ActivityGroupTemplateRead
 *
 * Activity group template read model
 */
export const zActivityGroupTemplateRead = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    activity_template_ids: z.array(z.uuid()).optional().default([])
});

/**
 * ActivityGroupUpdate
 *
 * Schema for assigning/updating an activity's group
 */
export const zActivityGroupUpdate = z.object({
    activity_group_id: z.uuid().nullish()
});

/**
 * ActivityPriority
 *
 * Possible activity priority levels
 */
export const zActivityPriority = z.enum([
    'Low',
    'Medium',
    'High',
    'Critical'
]);

/**
 * ActivityReorder
 *
 * Schema for reordering activities within a activity group
 */
export const zActivityReorder = z.object({
    activity_ids: z.array(z.uuid())
});

/**
 * ActivitySeverity
 *
 * Possible activity severity levels
 */
export const zActivitySeverity = z.enum([
    'Informational',
    'Low',
    'Medium',
    'High',
    'Critical'
]);

/**
 * ActivityState
 *
 * Possible activity state levels
 */
export const zActivityState = z.enum([
    'Pending',
    'Waiting Red',
    'Waiting Blue',
    'Ready',
    'In Progress',
    'In Evaluation',
    'Completed',
    'Cancelled'
]);

/**
 * ActivityTagsUpdate
 *
 * Schema for updating activity tags
 */
export const zActivityTagsUpdate = z.object({
    tag_ids: z.array(z.uuid()).optional().default([])
});

/**
 * ActivityTemplateRead
 *
 * Template activity read model
 */
export const zActivityTemplateRead = z.object({
    activity_actions: z.string().nullish(),
    activity_notes: z.string().nullish(),
    activity_rationale: z.string().nullish(),
    activity_requirements: z.string().nullish(),
    expected_logging: z.boolean().nullish(),
    expected_alert_creation: z.boolean().nullish(),
    expected_prevention: z.boolean().nullish(),
    expected_stakeholder_notification: z.boolean().nullish(),
    expected_severity: zActivitySeverity.nullish(),
    mitre_tactic: z.string(),
    mitre_technique: z.string(),
    name: z.string(),
    priority: zActivityPriority.nullish(),
    provider: z.string(),
    linked_knowledge_base_articles: z.array(z.string()).nullish(),
    id: z.uuid()
});

/**
 * AssessmentType
 *
 * Possible assessment types
 */
export const zAssessmentType = z.enum(['PurpleTeam', 'RedTeam']);

/**
 * AssessmentBase
 *
 * Shared properties for multiple assessment schemas
 */
export const zAssessmentBase = z.object({
    name: z.string().min(1),
    description: z.string().min(1),
    assessment_type: zAssessmentType.optional().default('PurpleTeam')
});

/**
 * AssessmentRead
 *
 * Properties to return via API for general assessment requests
 */
export const zAssessmentRead = z.object({
    name: z.string().min(1),
    description: z.string().min(1),
    assessment_type: zAssessmentType.optional().default('PurpleTeam'),
    id: z.uuid(),
    default_evaluation_templates: z.array(z.record(z.string(), z.union([
        z.string(),
        z.int()
    ])))
});

/**
 * AssetBase
 *
 * Asset base model
 */
export const zAssetBase = z.object({
    name: z.string(),
    icon: z.string().nullish(),
    properties: z.record(z.string(), z.unknown()).nullish()
});

/**
 * AssetRead
 *
 * Asset read model
 */
export const zAssetRead = z.object({
    name: z.string(),
    icon: z.string().nullish(),
    properties: z.record(z.string(), z.unknown()).nullish(),
    id: z.uuid(),
    deleted: z.boolean()
});

/**
 * Body_import_assessment_api_v1_assessment_import_post
 */
export const zBodyImportAssessmentApiV1AssessmentImportPost = z.object({
    file: z.string()
});

/**
 * Body_login_api_v1_auth_token_post
 */
export const zBodyLoginApiV1AuthTokenPost = z.object({
    grant_type: z.string().regex(/^password$/).nullish(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.string().nullish(),
    client_secret: z.string().nullish()
});

/**
 * Body_upload_file_api_v1_assessments__assessment_id__activity__activity_id__upload_post
 */
export const zBodyUploadFileApiV1AssessmentsAssessmentIdActivityActivityIdUploadPost = z.object({
    file: z.string()
});

/**
 * CampaignTemplateItemRead
 *
 * Campaign template item read model
 */
export const zCampaignTemplateItemRead = z.object({
    id: z.uuid(),
    position: z.int(),
    item_type: z.string(),
    activity_group_template_id: z.uuid().nullish(),
    activity_template_id: z.uuid().nullish()
});

/**
 * CampaignTemplateRead
 *
 * Campaign template read model
 */
export const zCampaignTemplateRead = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    items: z.array(zCampaignTemplateItemRead).optional().default([])
});

/**
 * DynamicEvaluationQuestionAssign
 *
 * Schema for assigning dynamic questions
 */
export const zDynamicEvaluationQuestionAssign = z.object({
    evaluation_template_id: z.uuid(),
    position: z.int().optional().default(0)
});

/**
 * EvaluationResult
 */
export const zEvaluationResult = z.enum([
    'pass',
    'fail',
    'n/a'
]);

/**
 * ActivityEvaluationDynamicQuestionsRead
 *
 * Read schema for activity evaluation dynamic questions
 */
export const zActivityEvaluationDynamicQuestionsRead = z.object({
    evaluation_template_id: z.uuid(),
    data: z.string().optional().default(''),
    evaluation_result: zEvaluationResult.optional().default('n/a'),
    position: z.int().optional().default(0),
    id: z.uuid()
});

/**
 * ActivityEvaluationDynamicQuestionsUpdate
 *
 * Update schema for activity evaluation dynamic questions
 */
export const zActivityEvaluationDynamicQuestionsUpdate = z.object({
    evaluation_template_id: z.uuid(),
    data: z.string().nullish(),
    evaluation_result: zEvaluationResult.nullish()
});

/**
 * ActivityEvaluationRead
 *
 * Activity Evaluation read schema
 */
export const zActivityEvaluationRead = z.object({
    logged_evaluation: zEvaluationResult.optional().default('n/a'),
    alerted_evaluation: zEvaluationResult.optional().default('n/a'),
    prevented_evaluation: zEvaluationResult.optional().default('n/a'),
    stakeholder_notified_evaluation: zEvaluationResult.optional().default('n/a'),
    activity_coverage_score: z.int().optional().default(0),
    event_to_alert_data: z.string().optional().default(''),
    event_to_alert_evaluation_result: zEvaluationResult.optional().default('n/a'),
    alert_to_stakeholder_data: z.string().optional().default(''),
    alert_to_stakeholder_evaluation_result: zEvaluationResult.optional().default('n/a'),
    alert_severity_data: z.string().optional().default(''),
    alert_severity_evaluation_result: zEvaluationResult.optional().default('n/a'),
    stakeholder_notification_severity_data: z.string().optional().default(''),
    stakeholder_notification_severity_evaluation_result: zEvaluationResult.optional().default('n/a'),
    dynamic_questions: z.array(zActivityEvaluationDynamicQuestionsRead).optional().default([]),
    id: z.uuid(),
    activity_id: z.uuid()
});

/**
 * ActivityEvaluationUpdate
 *
 * Activity Evaluation update schema
 */
export const zActivityEvaluationUpdate = z.object({
    logged_evaluation: zEvaluationResult.optional().default('n/a'),
    alerted_evaluation: zEvaluationResult.optional().default('n/a'),
    prevented_evaluation: zEvaluationResult.optional().default('n/a'),
    stakeholder_notified_evaluation: zEvaluationResult.optional().default('n/a'),
    activity_coverage_score: z.int().optional().default(0),
    event_to_alert_data: z.string().optional().default(''),
    event_to_alert_evaluation_result: zEvaluationResult.optional().default('n/a'),
    alert_to_stakeholder_data: z.string().optional().default(''),
    alert_to_stakeholder_evaluation_result: zEvaluationResult.optional().default('n/a'),
    alert_severity_data: z.string().optional().default(''),
    alert_severity_evaluation_result: zEvaluationResult.optional().default('n/a'),
    stakeholder_notification_severity_data: z.string().optional().default(''),
    stakeholder_notification_severity_evaluation_result: zEvaluationResult.optional().default('n/a'),
    dynamic_questions: z.array(zActivityEvaluationDynamicQuestionsUpdate).nullish()
});

/**
 * ActivityUpdate
 *
 * Assessment activity update model
 */
export const zActivityUpdate = z.object({
    name: z.string(),
    mitre_tactic: z.string(),
    mitre_technique: z.string(),
    provider: z.string().nullish(),
    visible: z.boolean().optional().default(false),
    priority: zActivityPriority.nullish(),
    state: zActivityState.nullable(),
    tags: z.array(z.uuid()).optional().default([]),
    activity_group_id: z.uuid().nullish(),
    updated_at: z.iso.datetime().nullish(),
    activity_rationale: z.string().nullish(),
    activity_actions: z.string().nullish(),
    activity_requirements: z.string().nullish(),
    activity_notes: z.string().nullish(),
    activity_start_time: z.iso.datetime().nullish(),
    activity_end_time: z.iso.datetime().nullish(),
    sources: z.array(z.uuid()).optional().default([]),
    targets: z.array(z.uuid()).optional().default([]),
    tools: z.array(z.uuid()).optional().default([]),
    expected_logging: z.boolean().nullish(),
    expected_prevention: z.boolean().nullish(),
    expected_alert_creation: z.boolean().nullish(),
    expected_stakeholder_notification: z.boolean().nullish(),
    expected_severity: zActivitySeverity.nullish(),
    log_sources: z.array(z.uuid()).optional().default([]),
    prevention_sources: z.array(z.uuid()).optional().default([]),
    alert_sources: z.array(z.uuid()).optional().default([]),
    stakeholder_notification_sources: z.array(z.uuid()).optional().default([]),
    logged: z.boolean().nullish(),
    log_time: z.iso.datetime().nullish(),
    prevented: z.boolean().nullish(),
    prevent_time: z.iso.datetime().nullish(),
    alerted: z.boolean().nullish(),
    alert_severity: zActivitySeverity.nullish(),
    alert_time: z.iso.datetime().nullish(),
    stakeholder_notification_created: z.boolean().nullish(),
    stakeholder_notification_severity: zActivitySeverity.nullish(),
    stakeholder_notification_time: z.iso.datetime().nullish(),
    linked_knowledge_base_articles: z.array(z.string()).nullish(),
    log_notes: z.string().nullish(),
    alert_notes: z.string().nullish(),
    prevent_notes: z.string().nullish(),
    stakeholder_notification_notes: z.string().nullish(),
    evaluation: zActivityEvaluationUpdate.nullish()
});

/**
 * EvaluationTemplateRead
 *
 * Schema for reading evaluation templates
 */
export const zEvaluationTemplateRead = z.object({
    name: z.string().optional().default(''),
    evaluation_criteria: z.string().optional().default(''),
    description: z.string().nullish(),
    id: z.uuid()
});

/**
 * ExternalAuthConfig
 *
 * Configuration for an external authentication provider
 */
export const zExternalAuthConfig = z.object({
    name: z.string(),
    configuration: z.string(),
    issuer: z.string(),
    jwks_url: z.string(),
    audience: z.string(),
    scope: z.string(),
    username_claim: z.string(),
    client_id: z.string(),
    trusted_email_domains: z.array(z.string())
});

/**
 * Configuration
 *
 * Configuration model for RAPTR
 */
export const zConfiguration = z.object({
    LOG_LEVEL: z.enum([
        'DEBUG',
        'INFO',
        'WARNING',
        'ERROR',
        'CRITICAL'
    ]),
    APPLICATION_NAME: z.string(),
    FASTAPI_DOCUMENTATION: z.boolean(),
    ADMIN_EMAIL: z.string(),
    MIN_PASSWORD_LENGTH: z.int(),
    OTP_LOCAL_ENABLED: z.boolean(),
    OTP_EXTERNAL_ENABLED: z.boolean(),
    CORS_ENABLED: z.boolean(),
    CORS_ORIGINS: z.array(z.string()),
    CORS_METHODS: z.array(z.string()),
    CORS_HEADERS: z.array(z.string()),
    CORS_CREDENTIALS: z.boolean(),
    CORS_MAX_AGE: z.int(),
    DB_ENGINE: z.enum(['postgres', 'sqlite']),
    SQLITE_DB_PATH: z.string(),
    POSTGRES_USER: z.string(),
    POSTGRES_DB: z.string(),
    POSTGRES_HOST: z.string(),
    POSTGRES_PORT: z.int(),
    ALGORITHM: z.string(),
    ACCESS_TOKEN_EXPIRE_MINUTES: z.int(),
    MITRE_JSON_URL: z.string(),
    CUSTOM_DATA_URL: z.string().nullable(),
    ATOMIC_RED_TEAM_URL: z.string(),
    WELCOME_MESSAGE: z.string().nullable(),
    EXTERNAL_AUTH_CONFIGS: z.array(zExternalAuthConfig).nullable()
});

/**
 * ExternalAuthProvider
 *
 * Configuration for an external authentication provider exposed to frontend
 */
export const zExternalAuthProvider = z.object({
    name: z.string(),
    authority: z.string(),
    client_id: z.string(),
    scope: z.string()
});

/**
 * FileCategory
 *
 * Possible file categories
 */
export const zFileCategory = z.enum(['red', 'blue']);

/**
 * FileType
 *
 * Possible file types
 */
export const zFileType = z.enum([
    'image/png',
    'image/jpeg',
    'image/jpg',
    'text/plain'
]);

/**
 * FileRead
 *
 * Model for reading file information
 */
export const zFileRead = z.object({
    filename: z.string(),
    content_type: zFileType,
    size: z.int(),
    category: zFileCategory,
    activity_id: z.uuid(),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    created_by: z.uuid()
});

/**
 * FileUploadResponse
 *
 * Response model for file uploads.
 */
export const zFileUploadResponse = z.object({
    message: z.string(),
    url: z.string(),
    file_id: z.uuid()
});

/**
 * ImportResponse
 */
export const zImportResponse = z.object({
    assessment_id: z.uuid(),
    message: z.string(),
    warnings: z.array(z.string()).optional().default([])
});

/**
 * KnowledgeBaseRead
 *
 * Knowledge Base Read Schema
 */
export const zKnowledgeBaseRead = z.object({
    name: z.string(),
    mitre_technique_id: z.string().nullish(),
    content: z.unknown().nullish(),
    id: z.uuid()
});

/**
 * MFASetupResponse
 *
 * Response for MFA setup containing provisioning URI
 */
export const zMfaSetupResponse = z.object({
    provisioning_uri: z.string(),
    message: z.string()
});

/**
 * MeanTimeMetricsItem
 */
export const zMeanTimeMetricsItem = z.object({
    priority: z.string(),
    mean_time_to_detect_seconds: z.number().nullable(),
    mean_time_to_respond_seconds: z.number().nullable()
});

/**
 * MessageResponse
 *
 * Standard message response
 */
export const zMessageResponse = z.object({
    message: z.string()
});

/**
 * MitreOverallTacticScoreItem
 */
export const zMitreOverallTacticScoreItem = z.object({
    tactic: z.string(),
    overall_score: z.number().nullable(),
    expected_logged_score: z.number().nullable(),
    logged_score: z.number().nullable(),
    expected_prevented_score: z.number().nullable(),
    prevented_score: z.number().nullable(),
    expected_alerted_score: z.number().nullable(),
    alerted_score: z.number().nullable(),
    expected_stakeholder_notified_score: z.number().nullable(),
    stakeholder_notified_score: z.number().nullable()
});

/**
 * MitreTechniqueScoreItem
 */
export const zMitreTechniqueScoreItem = z.object({
    technique: z.string(),
    overall_score: z.number().nullable(),
    expected_logged_score: z.number().nullable(),
    logged_score: z.number().nullable(),
    expected_prevented_score: z.number().nullable(),
    prevented_score: z.number().nullable(),
    expected_alerted_score: z.number().nullable(),
    alerted_score: z.number().nullable(),
    expected_stakeholder_notified_score: z.number().nullable(),
    stakeholder_notified_score: z.number().nullable()
});

/**
 * MitreTacticScoreItem
 */
export const zMitreTacticScoreItem = z.object({
    tactic: z.string(),
    techniques: z.array(zMitreTechniqueScoreItem)
});

/**
 * OTP
 *
 * OTP Schema
 */
export const zOtp = z.object({
    otp: z.string().length(6).regex(/^\d{6}$/)
});

/**
 * PaginatedResponse[ActivityGroupTemplateRead]
 */
export const zPaginatedResponseActivityGroupTemplateRead = z.object({
    items: z.array(zActivityGroupTemplateRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[ActivityTemplateRead]
 */
export const zPaginatedResponseActivityTemplateRead = z.object({
    items: z.array(zActivityTemplateRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[AssessmentRead]
 */
export const zPaginatedResponseAssessmentRead = z.object({
    items: z.array(zAssessmentRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[AssetRead]
 */
export const zPaginatedResponseAssetRead = z.object({
    items: z.array(zAssetRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[CampaignTemplateRead]
 */
export const zPaginatedResponseCampaignTemplateRead = z.object({
    items: z.array(zCampaignTemplateRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[EvaluationTemplateRead]
 */
export const zPaginatedResponseEvaluationTemplateRead = z.object({
    items: z.array(zEvaluationTemplateRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[KnowledgeBaseRead]
 */
export const zPaginatedResponseKnowledgeBaseRead = z.object({
    items: z.array(zKnowledgeBaseRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PriorityAverageScoreItem
 */
export const zPriorityAverageScoreItem = z.object({
    priority: z.string(),
    average_score: z.number().nullable()
});

/**
 * PriorityBreakdownItem
 */
export const zPriorityBreakdownItem = z.object({
    priority: z.string(),
    count: z.int()
});

/**
 * ReportContextRequest
 *
 * Schema for report context (data layer) request
 */
export const zReportContextRequest = z.object({
    sort_by: z.enum([
        'activity_position',
        'name',
        'mitre_tactic',
        'priority',
        'state',
        'start_time',
        'coverage_score'
    ]).optional().default('activity_position'),
    sort_order: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * ReportGenerateRequest
 *
 * Schema for report generation request
 */
export const zReportGenerateRequest = z.object({
    sort_by: z.enum([
        'activity_position',
        'name',
        'mitre_tactic',
        'priority',
        'state',
        'start_time',
        'coverage_score'
    ]).optional().default('activity_position'),
    sort_order: z.enum(['asc', 'desc']).optional().default('asc'),
    template_id: z.uuid()
});

/**
 * ReportTemplateFormat
 *
 * Possible report template formats
 */
export const zReportTemplateFormat = z.enum(['html', 'docx']);

/**
 * ReportTemplateRead
 *
 * Schema for reading report template
 */
export const zReportTemplateRead = z.object({
    filename: z.string(),
    format: zReportTemplateFormat,
    id: z.uuid()
});

/**
 * SeverityAccuracyItem
 */
export const zSeverityAccuracyItem = z.object({
    expected_severity: z.string(),
    actual_informational: z.int(),
    actual_low: z.int(),
    actual_medium: z.int(),
    actual_high: z.int(),
    actual_critical: z.int(),
    actual_none: z.int()
});

/**
 * StateDistributionItem
 */
export const zStateDistributionItem = z.object({
    state: z.string(),
    count: z.int()
});

/**
 * AssessmentStatisticsResponse
 */
export const zAssessmentStatisticsResponse = z.object({
    state_distribution: z.array(zStateDistributionItem),
    priority_breakdown: z.array(zPriorityBreakdownItem),
    average_coverage_score: z.number().nullish(),
    average_coverage_scores_by_priority: z.array(zPriorityAverageScoreItem),
    mitre_overall_tactic_scores: z.array(zMitreOverallTacticScoreItem),
    mitre_tactic_scores: z.array(zMitreTacticScoreItem),
    mean_time_metrics: z.array(zMeanTimeMetricsItem),
    severity_accuracy: z.array(zSeverityAccuracyItem)
});

/**
 * TacticBase
 *
 * Shared properties for multiple tactic schemas
 */
export const zTacticBase = z.object({
    id: z.uuid(),
    mitre_id: z.string(),
    name: z.string(),
    url: z.string().nullish()
});

/**
 * TagBase
 *
 * Shared properties for multiple tag schemas
 */
export const zTagBase = z.object({
    name: z.string(),
    color: z.string().regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)
});

/**
 * TagRead
 *
 * Properties to return via API for general tag requests
 */
export const zTagRead = z.object({
    name: z.string(),
    color: z.string().regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/),
    id: z.uuid(),
    deleted: z.boolean()
});

/**
 * ActivityRead
 *
 * Assessment activity read model
 */
export const zActivityRead = z.object({
    name: z.string(),
    mitre_tactic: z.string(),
    mitre_technique: z.string(),
    provider: z.string().nullish(),
    visible: z.boolean().optional().default(false),
    priority: zActivityPriority.nullish(),
    state: zActivityState.nullable(),
    tags: z.array(zTagRead).optional().default([]),
    activity_group_id: z.uuid().nullish(),
    updated_at: z.iso.datetime().nullish(),
    activity_rationale: z.string().nullish(),
    activity_actions: z.string().nullish(),
    activity_requirements: z.string().nullish(),
    activity_notes: z.string().nullish(),
    activity_start_time: z.iso.datetime().nullish(),
    activity_end_time: z.iso.datetime().nullish(),
    sources: z.array(zAssetRead).optional().default([]),
    targets: z.array(zAssetRead).optional().default([]),
    tools: z.array(zAssetRead).optional().default([]),
    expected_logging: z.boolean().nullish(),
    expected_prevention: z.boolean().nullish(),
    expected_alert_creation: z.boolean().nullish(),
    expected_stakeholder_notification: z.boolean().nullish(),
    expected_severity: zActivitySeverity.nullish(),
    log_sources: z.array(zAssetRead).optional().default([]),
    prevention_sources: z.array(zAssetRead).optional().default([]),
    alert_sources: z.array(zAssetRead).optional().default([]),
    stakeholder_notification_sources: z.array(zAssetRead).optional().default([]),
    logged: z.boolean().nullish(),
    log_time: z.iso.datetime().nullish(),
    prevented: z.boolean().nullish(),
    prevent_time: z.iso.datetime().nullish(),
    alerted: z.boolean().nullish(),
    alert_severity: zActivitySeverity.nullish(),
    alert_time: z.iso.datetime().nullish(),
    stakeholder_notification_created: z.boolean().nullish(),
    stakeholder_notification_severity: zActivitySeverity.nullish(),
    stakeholder_notification_time: z.iso.datetime().nullish(),
    linked_knowledge_base_articles: z.array(z.string()).nullish(),
    log_notes: z.string().nullish(),
    alert_notes: z.string().nullish(),
    prevent_notes: z.string().nullish(),
    stakeholder_notification_notes: z.string().nullish(),
    evaluation: zActivityEvaluationRead.nullish(),
    id: z.uuid(),
    deleted: z.boolean(),
    activity_position: z.int().nullish(),
    activity_group: zActivityGroupRead.nullish(),
    created_at: z.iso.datetime().nullish()
});

/**
 * PaginatedResponse[ActivityRead]
 */
export const zPaginatedResponseActivityRead = z.object({
    items: z.array(zActivityRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * PaginatedResponse[TagRead]
 */
export const zPaginatedResponseTagRead = z.object({
    items: z.array(zTagRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * TechniqueBase
 *
 * Shared properties for multiple technique schemas
 */
export const zTechniqueBase = z.object({
    id: z.uuid(),
    mitre_id: z.string(),
    name: z.string(),
    url: z.string().nullish()
});

/**
 * TacticWithTechniques
 *
 * Properties of a tactic with its associated techniques
 */
export const zTacticWithTechniques = z.object({
    id: z.uuid(),
    mitre_id: z.string(),
    name: z.string(),
    url: z.string().nullish(),
    techniques: z.array(zTechniqueBase)
});

/**
 * TechniqueWithTactics
 *
 * Properties of a technique with its associated tactics
 */
export const zTechniqueWithTactics = z.object({
    id: z.uuid(),
    mitre_id: z.string(),
    name: z.string(),
    url: z.string().nullish(),
    tactics: z.array(zTacticBase)
});

/**
 * Token
 *
 * JWT token response schema
 */
export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string(),
    next_url: z.string()
});

/**
 * UserPasswordMfaReset
 *
 * Properties to receive via API on user password MFA reset
 */
export const zUserPasswordMfaReset = z.object({
    password: z.string()
});

/**
 * UserPasswordReset
 *
 * Properties to receive via API on user password reset
 */
export const zUserPasswordReset = z.object({
    new_password: z.string()
});

/**
 * UserPasswordUpdate
 *
 * Properties to receive via API on user password update
 */
export const zUserPasswordUpdate = z.object({
    new_password: z.string(),
    old_password: z.string()
});

/**
 * UserRole
 *
 * Possible user roles
 */
export const zUserRole = z.enum(['admin', 'user']);

/**
 * UserBase
 *
 * Shared properties for multiple user schemas
 */
export const zUserBase = z.object({
    email: z.email(),
    role: zUserRole,
    disabled: z.boolean()
});

/**
 * ActivityHistoryRead
 *
 * Schema for reading a specific activity history, including the full snapshot.
 */
export const zActivityHistoryRead = z.object({
    activity_id: z.uuid(),
    version: z.int(),
    saved_at: z.iso.datetime(),
    saved_by_id: z.uuid().nullable(),
    snapshot: z.record(z.string(), z.unknown()),
    id: z.uuid(),
    saved_by: zUserBase.nullish()
});

/**
 * UserCreate
 *
 * Properties to receive via API on user creation. Password is required
 */
export const zUserCreate = z.object({
    email: z.email(),
    role: zUserRole,
    disabled: z.boolean(),
    password: z.string()
});

/**
 * UserRead
 *
 * Properties to return via API for general user requests
 */
export const zUserRead = z.object({
    email: z.email(),
    role: zUserRole,
    disabled: z.boolean(),
    id: z.uuid(),
    mfa_verified: z.boolean(),
    last_login_at: z.iso.datetime().nullable(),
    last_logout_at: z.iso.datetime().nullable()
});

/**
 * PaginatedResponse[UserRead]
 */
export const zPaginatedResponseUserRead = z.object({
    items: z.array(zUserRead),
    total: z.int(),
    page: z.int(),
    size: z.int(),
    pages: z.int()
});

/**
 * UserReadAcl
 *
 * Properties to return via API for general user requests, including ACLs
 */
export const zUserReadAcl = z.object({
    email: z.email(),
    role: zUserRole,
    disabled: z.boolean(),
    id: z.uuid(),
    mfa_verified: z.boolean(),
    last_login_at: z.iso.datetime().nullable(),
    last_logout_at: z.iso.datetime().nullable(),
    acl: z.array(zAclBase).nullish().default([])
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Successful Response
 */
export const zHealthCheckApiV1HealthGetResponse = zMessageResponse;

export const zLoginApiV1AuthTokenPostBody = zBodyLoginApiV1AuthTokenPost;

/**
 * Successful Response
 */
export const zLoginApiV1AuthTokenPostResponse = zToken;

/**
 * Successful Response
 */
export const zLogoutApiV1AuthLogoutPostResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zSetupMfaApiV1AuthMfaSetupPostResponse = zMfaSetupResponse;

export const zValidateMfaSetupApiV1AuthMfaSetupValidatePostBody = zOtp;

/**
 * Successful Response
 */
export const zValidateMfaSetupApiV1AuthMfaSetupValidatePostResponse = zToken;

export const zValidateMfaApiV1AuthMfaPostBody = zOtp;

/**
 * Successful Response
 */
export const zValidateMfaApiV1AuthMfaPostResponse = zToken;

/**
 * Response Get Providers Api V1 Auth Providers Get
 *
 * Successful Response
 */
export const zGetProvidersApiV1AuthProvidersGetResponse = z.array(zExternalAuthProvider);

/**
 * Successful Response
 */
export const zGetMotdApiV1AuthMotdGetResponse = zMessageResponse;

/**
 * Response Get Acls Api V1 Acl  Get
 *
 * Successful Response
 */
export const zGetAclsApiV1AclGetResponse = z.array(zAclRead);

export const zCreateAclApiV1AclPostBody = zAclBase;

/**
 * Successful Response
 */
export const zCreateAclApiV1AclPostResponse = zAclRead;

export const zDeleteAclApiV1AclAclIdDeletePath = z.object({
    acl_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteAclApiV1AclAclIdDeleteResponse = zMessageResponse;

export const zGetAclApiV1AclAclIdGetPath = z.object({
    acl_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAclApiV1AclAclIdGetResponse = zAclRead;

export const zUpdateAclApiV1AclAclIdPutBody = zAclBase;

export const zUpdateAclApiV1AclAclIdPutPath = z.object({
    acl_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAclApiV1AclAclIdPutResponse = zAclRead;

export const zGetAclsByAssessmentApiV1AclAssessmentAssessmentIdGetPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Response Get Acls By Assessment Api V1 Acl Assessment  Assessment Id  Get
 *
 * Successful Response
 */
export const zGetAclsByAssessmentApiV1AclAssessmentAssessmentIdGetResponse = z.array(zAclRead);

export const zGetAclsByUserApiV1AclUserUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Response Get Acls By User Api V1 Acl User  User Id  Get
 *
 * Successful Response
 */
export const zGetAclsByUserApiV1AclUserUserIdGetResponse = z.array(zAclRead);

export const zGetActivityTemplatesApiV1ActivityTemplateGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    mitre_tactic: z.string().nullish(),
    mitre_technique: z.string().nullish(),
    provider: z.string().nullish(),
    priority: z.array(zActivityPriority).nullish(),
    sort_by: z.enum([
        'name',
        'mitre_tactic',
        'mitre_technique',
        'provider',
        'priority'
    ]).nullish()
});

/**
 * Successful Response
 */
export const zGetActivityTemplatesApiV1ActivityTemplateGetResponse = zPaginatedResponseActivityTemplateRead;

export const zGetActivityTemplateApiV1ActivityTemplateActivityTemplateIdGetPath = z.object({
    activity_template_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetActivityTemplateApiV1ActivityTemplateActivityTemplateIdGetResponse = zActivityTemplateRead;

export const zGetActivityGroupTemplatesApiV1ActivityGroupTemplateGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    sort_by: z.literal('name').nullish()
});

/**
 * Successful Response
 */
export const zGetActivityGroupTemplatesApiV1ActivityGroupTemplateGetResponse = zPaginatedResponseActivityGroupTemplateRead;

export const zGetCampaignTemplatesApiV1CampaignTemplateGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    sort_by: z.literal('name').nullish()
});

/**
 * Successful Response
 */
export const zGetCampaignTemplatesApiV1CampaignTemplateGetResponse = zPaginatedResponseCampaignTemplateRead;

export const zGetCampaignTemplateApiV1CampaignTemplateCampaignTemplateIdGetPath = z.object({
    campaign_template_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetCampaignTemplateApiV1CampaignTemplateCampaignTemplateIdGetResponse = zCampaignTemplateRead;

export const zGetEvaluationTemplatesApiV1EvaluationTemplateGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    evaluation_criteria: z.string().nullish(),
    description: z.string().nullish(),
    sort_by: z.literal('name').nullish()
});

/**
 * Successful Response
 */
export const zGetEvaluationTemplatesApiV1EvaluationTemplateGetResponse = zPaginatedResponseEvaluationTemplateRead;

export const zGetEvaluationTemplateByIdApiV1EvaluationTemplateEvaluationTemplateIdGetPath = z.object({
    evaluation_template_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetEvaluationTemplateByIdApiV1EvaluationTemplateEvaluationTemplateIdGetResponse = zEvaluationTemplateRead;

export const zGetReportTemplatesApiV1ReportTemplateGetQuery = z.object({
    filename: z.string().nullish(),
    format: zReportTemplateFormat.nullish(),
    sort_by: z.enum(['filename', 'format']).optional().default('filename'),
    sort_order: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Response Get Report Templates Api V1 Report Template  Get
 *
 * Successful Response
 */
export const zGetReportTemplatesApiV1ReportTemplateGetResponse = z.array(zReportTemplateRead);

export const zGetKnowledgeBaseArticlesApiV1KnowledgeBaseGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    mitre_technique_id: z.string().nullish(),
    names: z.array(z.string()).nullish(),
    sort_by: z.enum(['name', 'mitre_technique_id']).nullish()
});

/**
 * Successful Response
 */
export const zGetKnowledgeBaseArticlesApiV1KnowledgeBaseGetResponse = zPaginatedResponseKnowledgeBaseRead;

export const zReadTacticsApiV1MitreTacticsGetQuery = z.object({
    name: z.string().nullish(),
    mitre_id: z.string().nullish(),
    sort_by: z.enum(['name', 'mitre_id']).nullish(),
    sort_order: z.enum(['asc', 'desc']).nullish()
});

/**
 * Response Read Tactics Api V1 Mitre Tactics Get
 *
 * Successful Response
 */
export const zReadTacticsApiV1MitreTacticsGetResponse = z.array(zTacticBase);

export const zReadTacticsWithTechniquesApiV1MitreTacticsWithTechniquesGetQuery = z.object({
    name: z.string().nullish(),
    mitre_id: z.string().nullish(),
    sort_by: z.enum(['name', 'mitre_id']).nullish(),
    sort_order: z.enum(['asc', 'desc']).nullish()
});

/**
 * Response Read Tactics With Techniques Api V1 Mitre Tactics With Techniques Get
 *
 * Successful Response
 */
export const zReadTacticsWithTechniquesApiV1MitreTacticsWithTechniquesGetResponse = z.array(zTacticWithTechniques);

export const zReadTechniquesApiV1MitreTechniquesGetQuery = z.object({
    name: z.string().nullish(),
    mitre_id: z.string().nullish(),
    sort_by: z.enum(['name', 'mitre_id']).nullish(),
    sort_order: z.enum(['asc', 'desc']).nullish()
});

/**
 * Response Read Techniques Api V1 Mitre Techniques Get
 *
 * Successful Response
 */
export const zReadTechniquesApiV1MitreTechniquesGetResponse = z.array(zTechniqueBase);

export const zReadTechniquesWithTacticsApiV1MitreTechniquesWithTacticsGetQuery = z.object({
    name: z.string().nullish(),
    mitre_id: z.string().nullish(),
    sort_by: z.enum(['name', 'mitre_id']).nullish(),
    sort_order: z.enum(['asc', 'desc']).nullish()
});

/**
 * Response Read Techniques With Tactics Api V1 Mitre Techniques With Tactics Get
 *
 * Successful Response
 */
export const zReadTechniquesWithTacticsApiV1MitreTechniquesWithTacticsGetResponse = z.array(zTechniqueWithTactics);

export const zReadUsersApiV1AdminUsersGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    email: z.string().nullish(),
    role: z.array(zUserRole).nullish(),
    disabled: z.array(z.boolean()).nullish(),
    mfa_verified: z.array(z.boolean()).nullish(),
    sort_by: z.enum([
        'email',
        'role',
        'disabled',
        'mfa_verified'
    ]).nullish()
});

/**
 * Successful Response
 */
export const zReadUsersApiV1AdminUsersGetResponse = zPaginatedResponseUserRead;

export const zDeleteUserApiV1AdminUsersUserIdDeletePath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteUserApiV1AdminUsersUserIdDeleteResponse = zMessageResponse;

export const zReadUserApiV1AdminUsersUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadUserApiV1AdminUsersUserIdGetResponse = zUserRead;

export const zUpdateUserApiV1AdminUsersUserIdPutBody = zUserBase;

export const zUpdateUserApiV1AdminUsersUserIdPutPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateUserApiV1AdminUsersUserIdPutResponse = zUserRead;

export const zCreateUserApiV1AdminUsersPostBody = zUserCreate;

/**
 * Successful Response
 */
export const zCreateUserApiV1AdminUsersPostResponse = zUserRead;

export const zResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostBody = zUserPasswordReset;

export const zResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostResponse = zMessageResponse;

export const zResetUserMfaApiV1AdminUsersUserIdResetMfaPostPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zResetUserMfaApiV1AdminUsersUserIdResetMfaPostResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zImportMitreTechniquesAndTacticsApiV1AdminSeedMitrePostResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zImportCustomDataApiV1AdminSeedCustomPostResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zImportAtomicRedTeamActivityTemplatesApiV1AdminSeedArtPostResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zGetConfigurationApiV1AdminConfigurationGetResponse = zConfiguration;

/**
 * Successful Response
 */
export const zReadUserSelfApiV1UserMeGetResponse = zUserReadAcl;

export const zUpdateUserPasswordSelfApiV1UserMePasswordPutBody = zUserPasswordUpdate;

/**
 * Successful Response
 */
export const zUpdateUserPasswordSelfApiV1UserMePasswordPutResponse = zMessageResponse;

export const zResetUserMfaSelfApiV1UserMeMfaPutBody = zUserPasswordMfaReset;

/**
 * Successful Response
 */
export const zResetUserMfaSelfApiV1UserMeMfaPutResponse = zMessageResponse;

export const zGetAssessmentsApiV1AssessmentGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    assessment_type: z.array(zAssessmentType).nullish(),
    sort_by: z.enum([
        'name',
        'assessment_type',
        'description'
    ]).nullish()
});

/**
 * Successful Response
 */
export const zGetAssessmentsApiV1AssessmentGetResponse = zPaginatedResponseAssessmentRead;

export const zCreateAssessmentApiV1AssessmentPostBody = zAssessmentBase;

/**
 * Successful Response
 */
export const zCreateAssessmentApiV1AssessmentPostResponse = zAssessmentRead;

export const zDeleteAssessmentApiV1AssessmentAssessmentIdDeletePath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteAssessmentApiV1AssessmentAssessmentIdDeleteResponse = zMessageResponse;

export const zGetAssessmentApiV1AssessmentAssessmentIdGetPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAssessmentApiV1AssessmentAssessmentIdGetResponse = zAssessmentRead;

export const zUpdateAssessmentApiV1AssessmentAssessmentIdPutBody = zAssessmentBase;

export const zUpdateAssessmentApiV1AssessmentAssessmentIdPutPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAssessmentApiV1AssessmentAssessmentIdPutResponse = zAssessmentRead;

export const zImportAssessmentApiV1AssessmentImportPostBody = zBodyImportAssessmentApiV1AssessmentImportPost;

/**
 * Successful Response
 */
export const zImportAssessmentApiV1AssessmentImportPostResponse = zImportResponse;

/**
 * Dynamic Evaluation Questions
 */
export const zUpdateAssessmentDefaultEvaluationTemplatesApiV1AssessmentAssessmentIdDefaultEvaluationTemplatesPutBody = z.array(zDynamicEvaluationQuestionAssign);

export const zUpdateAssessmentDefaultEvaluationTemplatesApiV1AssessmentAssessmentIdDefaultEvaluationTemplatesPutPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAssessmentDefaultEvaluationTemplatesApiV1AssessmentAssessmentIdDefaultEvaluationTemplatesPutResponse = zAssessmentRead;

export const zGetActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupGetPath = z.object({
    assessment_id: z.uuid()
});

export const zGetActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupGetQuery = z.object({
    name: z.string().nullish(),
    activity_group_position: z.int().nullish(),
    sort_by: z.enum(['name', 'activity_group_position']).nullish(),
    sort_order: z.enum(['asc', 'desc']).nullish()
});

/**
 * Response Get Activity Groups Api V1 Assessments  Assessment Id  Activity Group  Get
 *
 * Successful Response
 */
export const zGetActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupGetResponse = z.array(zActivityGroupRead);

export const zCreateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupPostBody = zActivityGroupBase;

export const zCreateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupPostResponse = zActivityGroupRead;

export const zGetActivityGroupApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdGetPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetActivityGroupApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdGetResponse = zActivityGroupRead;

export const zUpdateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdPutBody = zActivityGroupBase;

export const zUpdateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdPutPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateActivityGroupApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdPutResponse = zActivityGroupRead;

export const zGetActivityGroupActivitiesApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdActivitiesGetPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Response Get Activity Group Activities Api V1 Assessments  Assessment Id  Activity Group  Activity Group Id  Activities Get
 *
 * Successful Response
 */
export const zGetActivityGroupActivitiesApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdActivitiesGetResponse = z.array(zActivityRead);

export const zReorderActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupReorderPutBody = zActivityGroupReorder;

export const zReorderActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupReorderPutPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReorderActivityGroupsApiV1AssessmentsAssessmentIdActivityGroupReorderPutResponse = zMessageResponse;

export const zToggleActivityGroupDeleteApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdDeletePutPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleActivityGroupDeleteApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdDeletePutResponse = zMessageResponse;

export const zToggleActivityGroupVisibleApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdVisiblePutPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleActivityGroupVisibleApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdVisiblePutResponse = zMessageResponse;

export const zReorderActivitiesApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdReorderPutBody = zActivityReorder;

export const zReorderActivitiesApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdReorderPutPath = z.object({
    activity_group_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReorderActivitiesApiV1AssessmentsAssessmentIdActivityGroupActivityGroupIdReorderPutResponse = zMessageResponse;

export const zGetAllActivitiesApiV1AssessmentsAssessmentIdActivityGetPath = z.object({
    assessment_id: z.uuid()
});

export const zGetAllActivitiesApiV1AssessmentsAssessmentIdActivityGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    mitre_tactic: z.string().nullish(),
    mitre_technique: z.string().nullish(),
    priority: z.array(zActivityPriority).nullish(),
    state: z.array(zActivityState).nullish(),
    visible: z.boolean().nullish(),
    deleted: z.boolean().nullish(),
    tags: z.array(z.uuid()).nullish(),
    activity_group_id: z.uuid().nullish(),
    sort_by: z.enum([
        'name',
        'activity_position',
        'mitre_tactic',
        'mitre_technique',
        'priority',
        'state',
        'visible',
        'created_at',
        'updated_at',
        'activity_group.name',
        'activity_coverage_score',
        'activity_start_time',
        'activity_end_time',
        'tags'
    ]).nullish()
});

/**
 * Successful Response
 */
export const zGetAllActivitiesApiV1AssessmentsAssessmentIdActivityGetResponse = zPaginatedResponseActivityRead;

export const zCreateActivityApiV1AssessmentsAssessmentIdActivityPostBody = zActivityBase;

export const zCreateActivityApiV1AssessmentsAssessmentIdActivityPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateActivityApiV1AssessmentsAssessmentIdActivityPostResponse = zActivityRead;

export const zGetActivityByIdApiV1AssessmentsAssessmentIdActivityActivityIdGetPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetActivityByIdApiV1AssessmentsAssessmentIdActivityActivityIdGetResponse = zActivityRead;

export const zUpdateActivityApiV1AssessmentsAssessmentIdActivityActivityIdPutBody = zActivityUpdate;

export const zUpdateActivityApiV1AssessmentsAssessmentIdActivityActivityIdPutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateActivityApiV1AssessmentsAssessmentIdActivityActivityIdPutResponse = zActivityRead;

export const zToggleDeleteActivityStateApiV1AssessmentsAssessmentIdActivityActivityIdDeletePutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleDeleteActivityStateApiV1AssessmentsAssessmentIdActivityActivityIdDeletePutResponse = zMessageResponse;

export const zCloneActivityApiV1AssessmentsAssessmentIdActivityActivityIdClonePutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCloneActivityApiV1AssessmentsAssessmentIdActivityActivityIdClonePutResponse = zActivityRead;

export const zAssignUpdateActivityTagsApiV1AssessmentsAssessmentIdActivityActivityIdTagsPutBody = zActivityTagsUpdate;

export const zAssignUpdateActivityTagsApiV1AssessmentsAssessmentIdActivityActivityIdTagsPutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAssignUpdateActivityTagsApiV1AssessmentsAssessmentIdActivityActivityIdTagsPutResponse = zActivityRead;

export const zAssignUpdateActivityToActivityGroupApiV1AssessmentsAssessmentIdActivityActivityIdActivityGroupPutBody = zActivityGroupUpdate;

export const zAssignUpdateActivityToActivityGroupApiV1AssessmentsAssessmentIdActivityActivityIdActivityGroupPutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAssignUpdateActivityToActivityGroupApiV1AssessmentsAssessmentIdActivityActivityIdActivityGroupPutResponse = zActivityRead;

export const zAssignUpdateAssetsToActivityApiV1AssessmentsAssessmentIdActivityActivityIdAssetsRolePutBody = zActivityAssetUpdate;

export const zAssignUpdateAssetsToActivityApiV1AssessmentsAssessmentIdActivityActivityIdAssetsRolePutPath = z.object({
    activity_id: z.uuid(),
    role: zActivityAssetRole,
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAssignUpdateAssetsToActivityApiV1AssessmentsAssessmentIdActivityActivityIdAssetsRolePutResponse = zMessageResponse;

export const zToggleVisibleActivityApiV1AssessmentsAssessmentIdActivityActivityIdVisiblePutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleVisibleActivityApiV1AssessmentsAssessmentIdActivityActivityIdVisiblePutResponse = zMessageResponse;

/**
 * Dynamic Evaluation Questions
 */
export const zAssignDynamicEvaluationQuestionsApiV1AssessmentsAssessmentIdActivityActivityIdDynamicEvaluationQuestionsPutBody = z.array(zDynamicEvaluationQuestionAssign);

export const zAssignDynamicEvaluationQuestionsApiV1AssessmentsAssessmentIdActivityActivityIdDynamicEvaluationQuestionsPutPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAssignDynamicEvaluationQuestionsApiV1AssessmentsAssessmentIdActivityActivityIdDynamicEvaluationQuestionsPutResponse = zActivityRead;

export const zGetActivityFilesApiV1AssessmentsAssessmentIdActivityActivityIdFilesGetPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

export const zGetActivityFilesApiV1AssessmentsAssessmentIdActivityActivityIdFilesGetQuery = z.object({
    filename: z.string().nullish(),
    category: zFileCategory.nullish(),
    sort_by: z.enum(['filename', 'created_at']).nullish()
});

/**
 * Response Get Activity Files Api V1 Assessments  Assessment Id  Activity  Activity Id  Files Get
 *
 * Successful Response
 */
export const zGetActivityFilesApiV1AssessmentsAssessmentIdActivityActivityIdFilesGetResponse = z.array(zFileRead);

export const zDeleteActivityFileApiV1AssessmentsAssessmentIdActivityActivityIdFilesFileIdDeletePath = z.object({
    file_id: z.uuid(),
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteActivityFileApiV1AssessmentsAssessmentIdActivityActivityIdFilesFileIdDeleteResponse = zMessageResponse;

export const zGetActivityFileApiV1AssessmentsAssessmentIdActivityActivityIdFilesFileIdGetPath = z.object({
    activity_id: z.uuid(),
    file_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetActivityFileApiV1AssessmentsAssessmentIdActivityActivityIdFilesFileIdGetResponse = zFileRead;

export const zDownloadActivityFileApiV1AssessmentsAssessmentIdActivityActivityIdFilesFileIdDownloadGetPath = z.object({
    activity_id: z.uuid(),
    file_id: z.uuid(),
    assessment_id: z.uuid()
});

export const zUploadFileApiV1AssessmentsAssessmentIdActivityActivityIdUploadPostBody = zBodyUploadFileApiV1AssessmentsAssessmentIdActivityActivityIdUploadPost;

export const zUploadFileApiV1AssessmentsAssessmentIdActivityActivityIdUploadPostPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUploadFileApiV1AssessmentsAssessmentIdActivityActivityIdUploadPostResponse = zFileUploadResponse;

export const zGetActivityHistoryListApiV1AssessmentsAssessmentIdActivityActivityIdVersionGetPath = z.object({
    activity_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Response Get Activity History List Api V1 Assessments  Assessment Id  Activity  Activity Id  Version Get
 *
 * Successful Response
 */
export const zGetActivityHistoryListApiV1AssessmentsAssessmentIdActivityActivityIdVersionGetResponse = z.array(zActivityHistoryRead);

export const zGetActivityHistoryVersionApiV1AssessmentsAssessmentIdActivityActivityIdVersionVersionIdGetPath = z.object({
    activity_id: z.uuid(),
    version_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetActivityHistoryVersionApiV1AssessmentsAssessmentIdActivityActivityIdVersionVersionIdGetResponse = zActivityHistoryRead;

export const zGetAssetsApiV1AssessmentsAssessmentIdAssetGetPath = z.object({
    assessment_id: z.uuid()
});

export const zGetAssetsApiV1AssessmentsAssessmentIdAssetGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    deleted: z.boolean().nullish(),
    sort_by: z.enum(['name', 'deleted']).nullish()
});

/**
 * Successful Response
 */
export const zGetAssetsApiV1AssessmentsAssessmentIdAssetGetResponse = zPaginatedResponseAssetRead;

export const zCreateAssetApiV1AssessmentsAssessmentIdAssetPostBody = zAssetBase;

export const zCreateAssetApiV1AssessmentsAssessmentIdAssetPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateAssetApiV1AssessmentsAssessmentIdAssetPostResponse = zAssetRead;

export const zGetAssetApiV1AssessmentsAssessmentIdAssetAssetIdGetPath = z.object({
    asset_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAssetApiV1AssessmentsAssessmentIdAssetAssetIdGetResponse = zAssetRead;

export const zUpdateAssetApiV1AssessmentsAssessmentIdAssetAssetIdPutBody = zAssetBase;

export const zUpdateAssetApiV1AssessmentsAssessmentIdAssetAssetIdPutPath = z.object({
    asset_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAssetApiV1AssessmentsAssessmentIdAssetAssetIdPutResponse = zAssetRead;

export const zToggleAssetDeleteApiV1AssessmentsAssessmentIdAssetAssetIdDeletePutPath = z.object({
    asset_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleAssetDeleteApiV1AssessmentsAssessmentIdAssetAssetIdDeletePutResponse = zMessageResponse;

export const zGetTagsApiV1AssessmentsAssessmentIdTagGetPath = z.object({
    assessment_id: z.uuid()
});

export const zGetTagsApiV1AssessmentsAssessmentIdTagGetQuery = z.object({
    offset: z.int().optional().default(0),
    limit: z.int().optional().default(100),
    sort_order: z.enum(['asc', 'desc']).nullish(),
    name: z.string().nullish(),
    deleted: z.boolean().nullish(),
    sort_by: z.enum([
        'name',
        'color',
        'deleted'
    ]).nullish()
});

/**
 * Successful Response
 */
export const zGetTagsApiV1AssessmentsAssessmentIdTagGetResponse = zPaginatedResponseTagRead;

export const zCreateTagApiV1AssessmentsAssessmentIdTagPostBody = zTagBase;

export const zCreateTagApiV1AssessmentsAssessmentIdTagPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateTagApiV1AssessmentsAssessmentIdTagPostResponse = zTagRead;

export const zGetTagApiV1AssessmentsAssessmentIdTagTagIdGetPath = z.object({
    tag_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetTagApiV1AssessmentsAssessmentIdTagTagIdGetResponse = zTagRead;

export const zUpdateTagApiV1AssessmentsAssessmentIdTagTagIdPutBody = zTagBase;

export const zUpdateTagApiV1AssessmentsAssessmentIdTagTagIdPutPath = z.object({
    tag_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateTagApiV1AssessmentsAssessmentIdTagTagIdPutResponse = zTagRead;

export const zToggleTagDeleteApiV1AssessmentsAssessmentIdTagTagIdDeletePutPath = z.object({
    tag_id: z.uuid(),
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zToggleTagDeleteApiV1AssessmentsAssessmentIdTagTagIdDeletePutResponse = zMessageResponse;

/**
 * Activity Template Ids
 */
export const zImportFromActivityTemplatesApiV1AssessmentsAssessmentIdImportsActivityTemplatesPostBody = z.array(z.uuid());

export const zImportFromActivityTemplatesApiV1AssessmentsAssessmentIdImportsActivityTemplatesPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zImportFromActivityTemplatesApiV1AssessmentsAssessmentIdImportsActivityTemplatesPostResponse = zMessageResponse;

/**
 * Activity Group Template Ids
 */
export const zImportFromActivityGroupTemplatesApiV1AssessmentsAssessmentIdImportsActivityGroupTemplatesPostBody = z.array(z.uuid());

export const zImportFromActivityGroupTemplatesApiV1AssessmentsAssessmentIdImportsActivityGroupTemplatesPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zImportFromActivityGroupTemplatesApiV1AssessmentsAssessmentIdImportsActivityGroupTemplatesPostResponse = zMessageResponse;

export const zImportFromCampaignTemplateApiV1AssessmentsAssessmentIdImportsCampaignTemplatePostPath = z.object({
    assessment_id: z.uuid()
});

export const zImportFromCampaignTemplateApiV1AssessmentsAssessmentIdImportsCampaignTemplatePostQuery = z.object({
    campaign_template_id: z.uuid()
});

/**
 * Successful Response
 */
export const zImportFromCampaignTemplateApiV1AssessmentsAssessmentIdImportsCampaignTemplatePostResponse = zMessageResponse;

export const zGetReportContextApiV1AssessmentsAssessmentIdExportReportContextPostBody = zReportContextRequest;

export const zGetReportContextApiV1AssessmentsAssessmentIdExportReportContextPostPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Response Get Report Context Api V1 Assessments  Assessment Id  Export Report Context Post
 *
 * Successful Response
 */
export const zGetReportContextApiV1AssessmentsAssessmentIdExportReportContextPostResponse = z.record(z.string(), z.unknown());

export const zGenerateReportApiV1AssessmentsAssessmentIdExportReportGeneratePostBody = zReportGenerateRequest;

export const zGenerateReportApiV1AssessmentsAssessmentIdExportReportGeneratePostPath = z.object({
    assessment_id: z.uuid()
});

export const zGenerateMitreAttackNavigatorLayerApiV1AssessmentsAssessmentIdExportMitrePostPath = z.object({
    assessment_id: z.uuid()
});

export const zExportAssessmentApiV1AssessmentsAssessmentIdExportAssessmentPostPath = z.object({
    assessment_id: z.uuid()
});

export const zGetAssessmentStatisticsEndpointApiV1AssessmentsAssessmentIdStatisticsGetPath = z.object({
    assessment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAssessmentStatisticsEndpointApiV1AssessmentsAssessmentIdStatisticsGetResponse = zAssessmentStatisticsResponse;
